vim.o.number = true
vim.o.exrc=true
vim.o.relativenumber = true
vim.o.wrap = true
vim.o.copyindent = true
vim.o.tabstop = 2
vim.o.numberwidth = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.g.mapleader = ","
vim.g.maplocalleader=","
--vim.keymap.set('n','<Tab>',,{silent = true})
